### ISSUE TITLE
Inquiring Manual for Astrolabe 

### ISSUE THREAD

**Issue by NaphatCode** [twesigomwedavid/cyp2d6-gt-algorithms#1]
Hello David! First of all thank you for sharing your scripts, I am currently interested in CYP2D6 genotyping and your resource has been really helpful.

Currently, I am running into a problem with Astrolabe, as I found the documentation of this tools quite limited. My best strategy right now is following your scripts, but I would have to prepare required files by myself.

I wonder if you have access to the **manual/documentation of the Astrolabe** and if so, would it be possible for you to share it?

Best regards, Naphat

**Comment by twesigomwedavid** [comment]
Hi Naphat,

Thanks for reaching out.
I think the help menu for Astrolabe gives an idea of the options and expected arguments. Also, perhaps contacting the authors directly would be best. 

I would also recommend trying out [StellarPGx](https://github.com/SBIMB/StellarPGx), Aldy and/or PyPGx. 

Best regards

**Comment by NaphatCode** [comment]
Thank you so much for your instant support. I would try out tools and reach out the authors as you suggest.  Thank you again for sharing your insight!

**Comment by twesigomwedavid** [comment]
No worries
